--
-- PostgreSQL database dump
--



-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    event_id bigint NOT NULL,
    user_id bigint NOT NULL,
    event_type character varying(255) NOT NULL,
    event_date date NOT NULL,
    description character varying(255),
    id bigint NOT NULL
);


--
-- Name: events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.events ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    username character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id bigint NOT NULL,
    createdat timestamp(6) without time zone,
    emp_id bigint CONSTRAINT "users_Emp_ID_not_null" NOT NULL,
    access_level character varying(255),
    CONSTRAINT users_access_level_check CHECK (((access_level)::text = ANY ((ARRAY['READ'::character varying, 'READ_WRITE'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.events (event_id, user_id, event_type, event_date, description, id) VALUES (13, 6, 'Birthday', '2026-02-10', 'Romanane''s Birthday', 13);
INSERT INTO public.events (event_id, user_id, event_type, event_date, description, id) VALUES (15, 9, 'Birthday', '2026-02-12', 'Sagel''s 21st Birthday', 15);
INSERT INTO public.events (event_id, user_id, event_type, event_date, description, id) VALUES (16, 10, 'Birthday', '2026-02-13', 'Test Birthday!!', 16);


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level) VALUES (7, 'Romanane', 'iamromanane@gmail.com', '$2a$10$Ln7TrlU5JX2kFeiPvThOFedD7m9ZNb3S8UKAbf4ti0hGMN.JXKJ9a', '2026-02-10 17:47:04.467635', 7, NULL, 200, 'READ_WRITE');
INSERT INTO public.users (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level) VALUES (9, 'Sagel', 'sagel123@gmail.com', '$2a$10$AXX1WeELQD5cReQX66uPsudlIWvXt4T7ZV9a0VCzZ0jpmxw/7KcUy', '2026-02-11 13:00:33.795222', 9, NULL, 300, 'READ');
INSERT INTO public.users (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level) VALUES (10, 'test user', 'testuser@gmail.com', '$2a$10$ICSnMy9koEHtP8RXOd4EGekNBQsqdj3dMSXXbHU3TTMeu666kD07e', '2026-02-12 14:24:34.743961', 10, NULL, 400, 'READ_WRITE');
INSERT INTO public.users (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level) VALUES (11, 'xumotest', 'testuser123@gmail.com', '$2a$10$wD.oNdkdkiuTA3wcfawzhuBkUEqjp5Phtm1Afd93HodxKbKZ54ZEC', '2026-02-17 18:53:59.078815', 11, NULL, 500, 'READ');
INSERT INTO public.users (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level) VALUES (6, 'Admin', 'romananedandapani@gmail.com', '$2a$10$C4Cr4nrG16KG.sI6nl4JZ.TB25WzPd.ALOzgvEmvsf17qGJRMQ/aq', '2026-02-10 14:33:00.51907', 6, NULL, 100, 'READ_WRITE');
INSERT INTO public.users (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level) VALUES (12, 'testuser1', 'testuser1@gmail.com', '$2a$10$VklAcD5BL4.hibbmPuuRF.DH9L0kZgG.z5noLkgr99z3NPTu7RyrK', '2026-03-02 12:20:29.321732', 12, NULL, 600, 'READ');
INSERT INTO public.users (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level) VALUES (13, 'testuser2', 'testuser2@gmail.com', '$2a$10$xxWz8IUT39d74kbQLBgrKu.zct1Hd0GygHFXwHg3tIA9H0.5iWmXi', '2026-03-09 20:52:00.421826', 13, NULL, 700, 'READ_WRITE');


--
-- Name: events_event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.events_event_id_seq', 16, true);


--
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.events_id_seq', 16, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 13, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_user_id_seq', 13, true);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (event_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_emp_id_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_emp_id_unique UNIQUE (emp_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: events fk_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

