apiVersion: v1
data:
  init-data-clean.sql: "--\r\n-- PostgreSQL database dump\r\n--\r\n\r\n\r\n\r\n--
    Dumped from database version 18.1\r\n-- Dumped by pg_dump version 18.1\r\n\r\nSET
    statement_timeout = 0;\r\nSET lock_timeout = 0;\r\nSET idle_in_transaction_session_timeout
    = 0;\r\n\r\nSET client_encoding = 'UTF8';\r\nSET standard_conforming_strings =
    on;\r\nSELECT pg_catalog.set_config('search_path', '', false);\r\nSET check_function_bodies
    = false;\r\nSET xmloption = content;\r\nSET client_min_messages = warning;\r\nSET
    row_security = off;\r\n\r\nSET default_tablespace = '';\r\n\r\nSET default_table_access_method
    = heap;\r\n\r\n--\r\n-- Name: events; Type: TABLE; Schema: public; Owner: -\r\n--\r\n\r\nCREATE
    TABLE public.events (\r\n    event_id bigint NOT NULL,\r\n    user_id bigint NOT
    NULL,\r\n    event_type character varying(255) NOT NULL,\r\n    event_date date
    NOT NULL,\r\n    description character varying(255),\r\n    id bigint NOT NULL\r\n);\r\n\r\n\r\n--\r\n--
    Name: events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -\r\n--\r\n\r\nALTER
    TABLE public.events ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY
    (\r\n    SEQUENCE NAME public.events_event_id_seq\r\n    START WITH 1\r\n    INCREMENT
    BY 1\r\n    NO MINVALUE\r\n    NO MAXVALUE\r\n    CACHE 1\r\n);\r\n\r\n\r\n--\r\n--
    Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -\r\n--\r\n\r\nALTER
    TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (\r\n
    \   SEQUENCE NAME public.events_id_seq\r\n    START WITH 1\r\n    INCREMENT BY
    1\r\n    NO MINVALUE\r\n    NO MAXVALUE\r\n    CACHE 1\r\n);\r\n\r\n\r\n--\r\n--
    Name: users; Type: TABLE; Schema: public; Owner: -\r\n--\r\n\r\nCREATE TABLE public.users
    (\r\n    user_id bigint NOT NULL,\r\n    username character varying(255) NOT NULL,\r\n
    \   email character varying(255) NOT NULL,\r\n    password_hash character varying(255)
    NOT NULL,\r\n    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,\r\n
    \   id bigint NOT NULL,\r\n    createdat timestamp(6) without time zone,\r\n    emp_id
    bigint CONSTRAINT \"users_Emp_ID_not_null\" NOT NULL,\r\n    access_level character
    varying(255),\r\n    CONSTRAINT users_access_level_check CHECK (((access_level)::text
    = ANY ((ARRAY['READ'::character varying, 'READ_WRITE'::character varying])::text[])))\r\n);\r\n\r\n\r\n--\r\n--
    Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -\r\n--\r\n\r\nALTER
    TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (\r\n
    \   SEQUENCE NAME public.users_id_seq\r\n    START WITH 1\r\n    INCREMENT BY
    1\r\n    NO MINVALUE\r\n    NO MAXVALUE\r\n    CACHE 1\r\n);\r\n\r\n\r\n--\r\n--
    Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -\r\n--\r\n\r\nALTER
    TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (\r\n
    \   SEQUENCE NAME public.users_user_id_seq\r\n    START WITH 1\r\n    INCREMENT
    BY 1\r\n    NO MINVALUE\r\n    NO MAXVALUE\r\n    CACHE 1\r\n);\r\n\r\n\r\n--\r\n--
    Data for Name: events; Type: TABLE DATA; Schema: public; Owner: -\r\n--\r\n\r\nINSERT
    INTO public.events (event_id, user_id, event_type, event_date, description, id)
    VALUES (13, 6, 'Birthday', '2026-02-10', 'Romanane''s Birthday', 13);\r\nINSERT
    INTO public.events (event_id, user_id, event_type, event_date, description, id)
    VALUES (15, 9, 'Birthday', '2026-02-12', 'Sagel''s 21st Birthday', 15);\r\nINSERT
    INTO public.events (event_id, user_id, event_type, event_date, description, id)
    VALUES (16, 10, 'Birthday', '2026-02-13', 'Test Birthday!!', 16);\r\n\r\n\r\n--\r\n--
    Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -\r\n--\r\n\r\nINSERT
    INTO public.users (user_id, username, email, password_hash, created_at, id, createdat,
    emp_id, access_level) VALUES (7, 'Romanane', 'iamromanane@gmail.com', '$2a$10$Ln7TrlU5JX2kFeiPvThOFedD7m9ZNb3S8UKAbf4ti0hGMN.JXKJ9a',
    '2026-02-10 17:47:04.467635', 7, NULL, 200, 'READ_WRITE');\r\nINSERT INTO public.users
    (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level)
    VALUES (9, 'Sagel', 'sagel123@gmail.com', '$2a$10$AXX1WeELQD5cReQX66uPsudlIWvXt4T7ZV9a0VCzZ0jpmxw/7KcUy',
    '2026-02-11 13:00:33.795222', 9, NULL, 300, 'READ');\r\nINSERT INTO public.users
    (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level)
    VALUES (10, 'test user', 'testuser@gmail.com', '$2a$10$ICSnMy9koEHtP8RXOd4EGekNBQsqdj3dMSXXbHU3TTMeu666kD07e',
    '2026-02-12 14:24:34.743961', 10, NULL, 400, 'READ_WRITE');\r\nINSERT INTO public.users
    (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level)
    VALUES (11, 'xumotest', 'testuser123@gmail.com', '$2a$10$wD.oNdkdkiuTA3wcfawzhuBkUEqjp5Phtm1Afd93HodxKbKZ54ZEC',
    '2026-02-17 18:53:59.078815', 11, NULL, 500, 'READ');\r\nINSERT INTO public.users
    (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level)
    VALUES (6, 'Admin', 'romananedandapani@gmail.com', '$2a$10$C4Cr4nrG16KG.sI6nl4JZ.TB25WzPd.ALOzgvEmvsf17qGJRMQ/aq',
    '2026-02-10 14:33:00.51907', 6, NULL, 100, 'READ_WRITE');\r\nINSERT INTO public.users
    (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level)
    VALUES (12, 'testuser1', 'testuser1@gmail.com', '$2a$10$VklAcD5BL4.hibbmPuuRF.DH9L0kZgG.z5noLkgr99z3NPTu7RyrK',
    '2026-03-02 12:20:29.321732', 12, NULL, 600, 'READ');\r\nINSERT INTO public.users
    (user_id, username, email, password_hash, created_at, id, createdat, emp_id, access_level)
    VALUES (13, 'testuser2', 'testuser2@gmail.com', '$2a$10$xxWz8IUT39d74kbQLBgrKu.zct1Hd0GygHFXwHg3tIA9H0.5iWmXi',
    '2026-03-09 20:52:00.421826', 13, NULL, 700, 'READ_WRITE');\r\n\r\n\r\n--\r\n--
    Name: events_event_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -\r\n--\r\n\r\nSELECT
    pg_catalog.setval('public.events_event_id_seq', 16, true);\r\n\r\n\r\n--\r\n--
    Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -\r\n--\r\n\r\nSELECT
    pg_catalog.setval('public.events_id_seq', 16, true);\r\n\r\n\r\n--\r\n-- Name:
    users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -\r\n--\r\n\r\nSELECT
    pg_catalog.setval('public.users_id_seq', 13, true);\r\n\r\n\r\n--\r\n-- Name:
    users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -\r\n--\r\n\r\nSELECT
    pg_catalog.setval('public.users_user_id_seq', 13, true);\r\n\r\n\r\n--\r\n-- Name:
    events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -\r\n--\r\n\r\nALTER
    TABLE ONLY public.events\r\n    ADD CONSTRAINT events_pkey PRIMARY KEY (event_id);\r\n\r\n\r\n--\r\n--
    Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -\r\n--\r\n\r\nALTER
    TABLE ONLY public.users\r\n    ADD CONSTRAINT users_email_key UNIQUE (email);\r\n\r\n\r\n--\r\n--
    Name: users users_emp_id_unique; Type: CONSTRAINT; Schema: public; Owner: -\r\n--\r\n\r\nALTER
    TABLE ONLY public.users\r\n    ADD CONSTRAINT users_emp_id_unique UNIQUE (emp_id);\r\n\r\n\r\n--\r\n--
    Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -\r\n--\r\n\r\nALTER
    TABLE ONLY public.users\r\n    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);\r\n\r\n\r\n--\r\n--
    Name: events fk_user; Type: FK CONSTRAINT; Schema: public; Owner: -\r\n--\r\n\r\nALTER
    TABLE ONLY public.events\r\n    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES
    public.users(user_id) ON DELETE CASCADE;\r\n\r\n\r\n--\r\n-- PostgreSQL database
    dump complete\r\n--\r\n\r\n"
kind: ConfigMap
metadata:
  name: postgres-init-data
